// Mock data for demo functionality (no database required)

import type {
  User,
  StaffProfile,
  Shift,
  ShiftAssignment,
  TimeOffBank,
  ShiftSwapRequest,
  ChatConversation,
  ChatMessage,
  StaffAvailability,
  Skill,
} from './definitions';

// Current user (Staff member)
export const currentUser: User = {
  id: 'user_1',
  name: 'Michael Chen',
  email: 'michael.chen@cityhospital.org',
  phone: '(555) 123-4567',
  employeeNumber: 'EMP002',
  timezone: 'America/New_York',
  emailVerified: true,
  image: null,
  createdAt: new Date('2015-06-01'),
  updatedAt: new Date(),
  currentOrganizationId: 'org_1',
  isSuperAdmin: false,
};

export const currentStaffProfile: StaffProfile = {
  id: 'staff_1',
  userId: 'user_1',
  organizationId: 'org_1',
  collectiveAgreementId: 'cba_1',
  departmentId: 'dept_1',
  managerId: 'staff_manager',
  seniorityDate: new Date('2015-06-01'),
  hireDate: new Date('2015-06-01'),
  jobTitle: 'Registered Nurse',
  workSchedulePattern: '4 on 4 off',
  createdAt: new Date('2015-06-01'),
  updatedAt: new Date(),
};

// Upcoming shifts for current user
export const upcomingShifts: (Shift & { assignment: ShiftAssignment })[] = [
  {
    id: 'shift_1',
    scheduleId: 'schedule_1',
    organizationId: 'org_1',
    shiftDate: new Date(Date.now()),
    startTime: '07:00',
    endTime: '15:00',
    shiftType: 'Day',
    location: 'Emergency Department',
    minStaffing: 2,
    targetStaffing: 3,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    assignment: {
      id: 'assign_1',
      shiftId: 'shift_1',
      staffProfileId: 'staff_1',
      status: 'CONFIRMED',
      assignedAt: new Date(),
      confirmedAt: new Date(),
      notes: null,
      triggersOT: false,
      triggersPremium: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
  {
    id: 'shift_2',
    scheduleId: 'schedule_1',
    organizationId: 'org_1',
    shiftDate: new Date(Date.now() + 86400000),
    startTime: '15:00',
    endTime: '23:00',
    shiftType: 'Evening',
    location: 'Emergency Department',
    minStaffing: 2,
    targetStaffing: 3,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    assignment: {
      id: 'assign_2',
      shiftId: 'shift_2',
      staffProfileId: 'staff_1',
      status: 'CONFIRMED',
      assignedAt: new Date(),
      confirmedAt: new Date(),
      notes: null,
      triggersOT: false,
      triggersPremium: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
  {
    id: 'shift_3',
    scheduleId: 'schedule_1',
    organizationId: 'org_1',
    shiftDate: new Date(Date.now() + 86400000 * 2),
    startTime: '07:00',
    endTime: '15:00',
    shiftType: 'Day',
    location: 'Emergency Department',
    minStaffing: 2,
    targetStaffing: 3,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    assignment: {
      id: 'assign_3',
      shiftId: 'shift_3',
      staffProfileId: 'staff_1',
      status: 'CONFIRMED',
      assignedAt: new Date(),
      confirmedAt: new Date(),
      notes: null,
      triggersOT: false,
      triggersPremium: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
  {
    id: 'shift_4',
    scheduleId: 'schedule_1',
    organizationId: 'org_1',
    shiftDate: new Date(Date.now() + 86400000 * 5),
    startTime: '07:00',
    endTime: '15:00',
    shiftType: 'Day',
    location: 'Emergency Department',
    minStaffing: 2,
    targetStaffing: 3,
    notes: 'High volume expected',
    createdAt: new Date(),
    updatedAt: new Date(),
    assignment: {
      id: 'assign_4',
      shiftId: 'shift_4',
      staffProfileId: 'staff_1',
      status: 'SCHEDULED',
      assignedAt: new Date(),
      confirmedAt: null,
      notes: null,
      triggersOT: false,
      triggersPremium: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
];

// Time off banks
export const timeOffBanks: TimeOffBank[] = [
  {
    id: 'bank_1',
    staffProfileId: 'staff_1',
    bankType: 'VACATION',
    balanceHours: 120,
    expiryDate: null,
    accrualRate: 10,
    yearGranted: 2024,
    notes: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'bank_2',
    staffProfileId: 'staff_1',
    bankType: 'STAT_DAY',
    balanceHours: 24,
    expiryDate: new Date(Date.now() + 30 * 86400000), // 30 days
    accrualRate: null,
    yearGranted: 2024,
    notes: 'Expiring soon!',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'bank_3',
    staffProfileId: 'staff_1',
    bankType: 'PERSONAL_DAY',
    balanceHours: 16,
    expiryDate: new Date(Date.now() + 60 * 86400000), // 60 days
    accrualRate: null,
    yearGranted: 2024,
    notes: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'bank_4',
    staffProfileId: 'staff_1',
    bankType: 'SICK_TIME',
    balanceHours: 40,
    expiryDate: null,
    accrualRate: 4,
    yearGranted: null,
    notes: 'Rolls over annually',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
];

// Active shift swap request
export const activeShiftSwapRequest: ShiftSwapRequest = {
  id: 'swap_1',
  requestingStaffId: 'staff_1',
  targetStaffId: null,
  originalShiftId: 'shift_4',
  swapShiftId: null,
  status: 'PENDING',
  requestReason: 'Family event - need Thursday off',
  aiSuggestions: {
    suggestions: [
      {
        staffId: 'staff_2',
        staffName: 'Emily Rodriguez',
        employeeNumber: 'EMP003',
        seniority: 6.2,
        compatibility: {
          skillsMatch: true,
          availabilityMatch: true,
          noViolations: true,
          swapLimitOk: true,
        },
        details: {
          skills: ['RN', 'ACLS'],
          currentSwaps: 1,
          maxSwaps: 3,
          violations: [],
        },
        score: 95,
      },
      {
        staffId: 'staff_3',
        staffName: 'James Wilson',
        employeeNumber: 'EMP004',
        seniority: 2.8,
        compatibility: {
          skillsMatch: true,
          availabilityMatch: true,
          noViolations: true,
          swapLimitOk: true,
        },
        details: {
          skills: ['RN'],
          currentSwaps: 0,
          maxSwaps: 3,
          violations: [],
        },
        score: 88,
      },
    ],
  },
  skillsMatched: true,
  triggersViolations: null,
  approvedBy: null,
  approvedAt: null,
  deniedReason: null,
  createdAt: new Date(),
  updatedAt: new Date(),
};

// Chat conversation for availability submission
export const chatConversations: ChatConversation[] = [
  {
    id: 'conv_1',
    staffProfileId: 'staff_1',
    conversationType: 'AVAILABILITY_SUBMISSION',
    context: {
      scheduleId: 'schedule_1',
      currentStep: 'reviewing_availability',
    },
    lastMessageAt: new Date(),
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'conv_2',
    staffProfileId: 'staff_1',
    conversationType: 'SHIFT_SWAP',
    context: {
      swapRequestId: 'swap_1',
      originalShiftId: 'shift_4',
    },
    lastMessageAt: new Date(Date.now() - 3600000),
    isActive: true,
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(Date.now() - 3600000),
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'msg_1',
    conversationId: 'conv_1',
    role: 'assistant',
    content:
      "Hi Michael! It's time to submit your availability for next month's schedule. Would you like to do that now?",
    metadata: {
      action: 'availability_reminder',
      scheduleId: 'schedule_1',
    },
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: 'msg_2',
    conversationId: 'conv_1',
    role: 'user',
    content: 'Yes, please!',
    metadata: null,
    createdAt: new Date(Date.now() - 7000000),
  },
  {
    id: 'msg_3',
    conversationId: 'conv_1',
    role: 'assistant',
    content:
      "Great! Let me show you your current schedule. You're working 12 shifts this period totaling 96 hours. According to the CBA, you need to provide at least 20 hours of availability per week for next period. Would you like me to suggest some availability slots based on your typical pattern?",
    metadata: {
      currentHours: 96,
      cbaRequirement: 20,
      weeklyAverage: 24,
    },
    createdAt: new Date(Date.now() - 6800000),
  },
  {
    id: 'msg_4',
    conversationId: 'conv_1',
    role: 'user',
    content: 'Yes, that would be helpful',
    metadata: null,
    createdAt: new Date(Date.now() - 6600000),
  },
  {
    id: 'msg_5',
    conversationId: 'conv_1',
    role: 'assistant',
    content:
      "Based on your 4-on-4-off pattern and preference for day shifts, I suggest:\n\n✅ Week 1: Mon, Tue, Wed, Thu (Day shifts) - 32 hours\n✅ Week 2: Mon, Tue, Wed (Day shifts) - 24 hours\n✅ Week 3: Thu, Fri (Day shifts) + Sat (Evening) - 24 hours\n\nTotal: 80 hours (exceeds 60 hour minimum)\n\nThis keeps you below the 5 consecutive shift limit and avoids back-to-back weekends per CBA rules. Should I submit this availability?",
    metadata: {
      suggestedHours: 80,
      meetsRequirements: true,
      violations: [],
    },
    createdAt: new Date(Date.now() - 6400000),
  },
];

// Staff for swap suggestions
export const otherStaff = [
  {
    id: 'staff_2',
    name: 'Emily Rodriguez',
    employeeNumber: 'EMP003',
    jobTitle: 'Registered Nurse',
    seniorityYears: 6.2,
  },
  {
    id: 'staff_3',
    name: 'James Wilson',
    employeeNumber: 'EMP004',
    jobTitle: 'Registered Nurse',
    seniorityYears: 2.8,
  },
];

// Skills
export const skills: Skill[] = [
  {
    id: 'skill_1',
    name: 'Registered Nurse',
    description: 'RN certification',
    organizationId: 'org_1',
    requiresCertification: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'skill_2',
    name: 'ACLS Certified',
    description: 'Advanced Cardiac Life Support',
    organizationId: 'org_1',
    requiresCertification: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'skill_3',
    name: 'Trauma Certified',
    description: 'Trauma nursing certification',
    organizationId: 'org_1',
    requiresCertification: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
